# Generated by Django 2.1.2 on 2019-03-19 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('african_traje', models.BooleanField(default=False)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/clothing/')),
                ('Popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/hair/')),
                ('Popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('african_traje', models.BooleanField(default=False)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/shoes/')),
                ('Popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
