# Generated by Django 2.1.2 on 2019-03-19 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('african_traje', models.BooleanField(default=False)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/clothes/')),
                ('Popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
