# Generated by Django 2.1.2 on 2019-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190319_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='type',
            field=models.CharField(default='blusa', max_length=100),
        ),
    ]
