# Generated by Django 2.1.2 on 2019-03-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_cloth_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='Popularity',
            new_name='popularity',
        ),
        migrations.RenameField(
            model_name='hair',
            old_name='Popularity',
            new_name='popularity',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='Popularity',
            new_name='popularity',
        ),
    ]
