# Generated by Django 2.1.2 on 2019-03-26 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190319_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/sections/')),
            ],
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='hair',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='data',
            new_name='date',
        ),
    ]
