# Generated by Django 2.1.2 on 2019-03-26 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190326_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='Roupa', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.BooleanField(default=False)),
                ('african_traje', models.BooleanField(default=False)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/items/')),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
