# Generated by Django 2.1.2 on 2019-03-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/item/photo')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Item')),
            ],
        ),
    ]
