# Generated by Django 2.1.2 on 2019-04-22 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_photoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('highlight_sentence', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('artwork', models.ImageField(default=' ', max_length=45, upload_to='uploads/sections/')),
            ],
        ),
    ]
